### ISSUE TITLE
Can I convert a ULID to a UUIDv4 form with this library?

### ISSUE THREAD

**Issue by henricook** [aarondcohen/id128#26]
Firstly, this library looks great so thanks for that. Especially when storing ULIDs in Postgres I've found it's nicer to do that in UUID form. Reasons for that aside... can I use this library to convert a ULID to a UUID? and vice versa?

**Comment by aarondcohen** [comment]
the answer is sort of.  from a technical point of view,  all of the ids support `.bytes` so you can pass the bytes to a constructor of another type.  however, the bit layout of the various types is pretty different so you'll end up creating invalid ids.  in particular:
- Ulid: prefixed with a timestamp so converting from a uuid4 will result in a random timestamp
- Uuid4: has variant and version bits so converting from a ulid will likely not match those bits

Uuid6 bridges Ulid and Uuid4 (it's essentially a Ulid with version/variant set).

if you're saving to postgres, make sure to use the uuid type (there's an extension for it) instead of char/varchar/text as it will use proper bit packing.  the `.toRaw` function should allow you to write an id into the db without needing to cast between the types.  hope this helps.
